/*
 * esdb-schema: ES3-safe ExtendScript repository facade.
 *
 * The generated facade calls named generated bridge operations only. It never
 * builds, sends, or accepts SQL text; all SQL lives in the C++ lane and the
 * migration package. Values cross the ESABI bridge through the U1 wire
 * contract documented in bridge/<schema>_orm_bridge.h.
 */

import { columnByName, deriveApiParams, tableByName } from "./ir.mjs";
import { bridgeDefaultLibrary, bridgeFunctionName, es3GlobalName, querySurfaceName } from "./naming.mjs";

function planQuery(ir, schema, table, query) {
    return {
        method: querySurfaceName(schema, query.name),
        bridge: bridgeFunctionName(schema, query.name),
        kind: query.kind,
        cardinality: query.cardinality,
        columns: table.columns.map((column) => column.name),
        columnTypes: table.columns.map((column) => column.type),
        columnNullable: table.columns.map((column) => column.nullable === true),
        params: deriveApiParams(table, query, ir).map((param) => {
            const owner = param.table === null || param.table === table.name ? table : tableByName(ir, param.table);
            const column = param.column === null || owner === null ? null : columnByName(owner, param.column);
            return {
                name: param.name,
                type: param.type,
                nullable: column !== null && column.nullable === true
            };
        })
    };
}

function emitHelpers(global, lines) {
    lines.push(`    function hexByte(value) {`);
    lines.push(`        var digits = "0123456789ABCDEF";`);
    lines.push(`        return digits.charAt((value >>> 4) & 15) + digits.charAt(value & 15);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function utf8ToHex(value) {`);
    lines.push(`        var text = String(value);`);
    lines.push(`        var out = [];`);
    lines.push(`        var i;`);
    lines.push(`        var code;`);
    lines.push(`        var low;`);
    lines.push(`        var point;`);
    lines.push(`        for (i = 0; i < text.length; i += 1) {`);
    lines.push(`            code = text.charCodeAt(i);`);
    lines.push(`            if (code <= 0x7f) {`);
    lines.push(`                out[out.length] = hexByte(code);`);
    lines.push(`            } else if (code <= 0x7ff) {`);
    lines.push(`                out[out.length] = hexByte(0xc0 | (code >>> 6));`);
    lines.push(`                out[out.length] = hexByte(0x80 | (code & 0x3f));`);
    lines.push(`            } else if (code >= 0xd800 && code <= 0xdbff) {`);
    lines.push(`                if (i + 1 >= text.length) {`);
    lines.push(`                    fail("unpaired high surrogate in string");`);
    lines.push(`                }`);
    lines.push(`                low = text.charCodeAt(i + 1);`);
    lines.push(`                if (low < 0xdc00 || low > 0xdfff) {`);
    lines.push(`                    fail("unpaired high surrogate in string");`);
    lines.push(`                }`);
    lines.push(`                point = 0x10000 + ((code - 0xd800) << 10) + (low - 0xdc00);`);
    lines.push(`                out[out.length] = hexByte(0xf0 | (point >>> 18));`);
    lines.push(`                out[out.length] = hexByte(0x80 | ((point >>> 12) & 0x3f));`);
    lines.push(`                out[out.length] = hexByte(0x80 | ((point >>> 6) & 0x3f));`);
    lines.push(`                out[out.length] = hexByte(0x80 | (point & 0x3f));`);
    lines.push(`                i += 1;`);
    lines.push(`            } else if (code >= 0xdc00 && code <= 0xdfff) {`);
    lines.push(`                fail("unpaired low surrogate in string");`);
    lines.push(`            } else {`);
    lines.push(`                out[out.length] = hexByte(0xe0 | (code >>> 12));`);
    lines.push(`                out[out.length] = hexByte(0x80 | ((code >>> 6) & 0x3f));`);
    lines.push(`                out[out.length] = hexByte(0x80 | (code & 0x3f));`);
    lines.push(`            }`);
    lines.push(`        }`);
    lines.push(`        return out.join("");`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function nibble(code) {`);
    lines.push(`        if (code >= 48 && code <= 57) {`);
    lines.push(`            return code - 48;`);
    lines.push(`        }`);
    lines.push(`        if (code >= 65 && code <= 70) {`);
    lines.push(`            return code - 55;`);
    lines.push(`        }`);
    lines.push(`        if (code >= 97 && code <= 102) {`);
    lines.push(`            return code - 87;`);
    lines.push(`        }`);
    lines.push(`        return -1;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function normalizeHex(value) {`);
    lines.push(`        var text = String(value);`);
    lines.push(`        var i;`);
    lines.push(`        if ((text.length & 1) != 0) {`);
    lines.push(`            fail("hex payload must contain an even number of digits");`);
    lines.push(`        }`);
    lines.push(`        for (i = 0; i < text.length; i += 1) {`);
    lines.push(`            if (nibble(text.charCodeAt(i)) < 0) {`);
    lines.push(`                fail("hex payload contains a non-hex character");`);
    lines.push(`            }`);
    lines.push(`        }`);
    lines.push(`        return text.toUpperCase();`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function hexToUtf8(hex) {`);
    lines.push(`        var text = String(hex);`);
    lines.push(`        var out = "";`);
    lines.push(`        var i;`);
    lines.push(`        var b;`);
    lines.push(`        var b2;`);
    lines.push(`        var code;`);
    lines.push(`        var extra;`);
    lines.push(`        var j;`);
    lines.push(`        if ((text.length & 1) != 0) {`);
    lines.push(`            fail("hex payload must contain an even number of digits");`);
    lines.push(`        }`);
    lines.push(`        for (i = 0; i < text.length; i += 2) {`);
    lines.push(`            b = (nibble(text.charCodeAt(i)) << 4) | nibble(text.charCodeAt(i + 1));`);
    lines.push(`            if (b < 0) {`);
    lines.push(`                fail("hex payload contains a non-hex character");`);
    lines.push(`            }`);
    lines.push(`            if (b < 0x80) {`);
    lines.push(`                out += String.fromCharCode(b);`);
    lines.push(`            } else {`);
    lines.push(`                if (b >= 0xc2 && b <= 0xdf) {`);
    lines.push(`                    extra = 1;`);
    lines.push(`                    code = b & 0x1f;`);
    lines.push(`                } else if (b >= 0xe0 && b <= 0xef) {`);
    lines.push(`                    extra = 2;`);
    lines.push(`                    code = b & 0x0f;`);
    lines.push(`                } else if (b >= 0xf0 && b <= 0xf4) {`);
    lines.push(`                    extra = 3;`);
    lines.push(`                    code = b & 0x07;`);
    lines.push(`                } else {`);
    lines.push(`                    fail("invalid UTF-8 lead byte");`);
    lines.push(`                }`);
    lines.push(`                if (i + extra * 2 + 2 > text.length) {`);
    lines.push(`                    fail("truncated UTF-8 sequence");`);
    lines.push(`                }`);
    lines.push(`                for (j = 0; j < extra; j += 1) {`);
    lines.push(`                    b2 = (nibble(text.charCodeAt(i + 2 + j * 2)) << 4) | nibble(text.charCodeAt(i + 3 + j * 2));`);
    lines.push(`                    if (b2 < 0x80 || b2 > 0xbf) {`);
    lines.push(`                        fail("invalid UTF-8 continuation byte");`);
    lines.push(`                    }`);
    lines.push(`                    if (j == 0) {`);
    lines.push(`                        if (b == 0xe0 && b2 < 0xa0) fail("overlong UTF-8 sequence");`);
    lines.push(`                        if (b == 0xed && b2 >= 0xa0) fail("UTF-8 encodes a surrogate");`);
    lines.push(`                        if (b == 0xf0 && b2 < 0x90) fail("overlong UTF-8 sequence");`);
    lines.push(`                        if (b == 0xf4 && b2 >= 0x90) fail("UTF-8 code point exceeds U+10FFFF");`);
    lines.push(`                    }`);
    lines.push(`                    code = (code << 6) | (b2 & 0x3f);`);
    lines.push(`                }`);
    lines.push(`                i += extra * 2;`);
    lines.push(`                if (code > 0xffff) {`);
    lines.push(`                    code -= 0x10000;`);
    lines.push(`                    out += String.fromCharCode(0xd800 + (code >> 10), 0xdc00 + (code & 0x3ff));`);
    lines.push(`                } else {`);
    lines.push(`                    out += String.fromCharCode(code);`);
    lines.push(`                }`);
    lines.push(`            }`);
    lines.push(`        }`);
    lines.push(`        return out;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function int64TextInRange(text) {`);
    lines.push(`        var negative = text.charAt(0) == "-";`);
    lines.push(`        var digits = negative ? text.substring(1) : text;`);
    lines.push(`        var limit = negative ? "9223372036854775808" : "9223372036854775807";`);
    lines.push(`        digits = digits.replace(/^0+/, "");`);
    lines.push(`        if (digits.length == 0) {`);
    lines.push(`            digits = "0";`);
    lines.push(`        }`);
    lines.push(`        if (digits.length != limit.length) {`);
    lines.push(`            return digits.length < limit.length;`);
    lines.push(`        }`);
    lines.push(`        return digits <= limit;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function int64ToWire(value) {`);
    lines.push(`        var text;`);
    lines.push(`        if (typeof value == "number") {`);
    lines.push(`            if (!isFinite(value) || Math.floor(value) != value) {`);
    lines.push(`                fail("integer parameter must be a whole number");`);
    lines.push(`            }`);
    lines.push(`            if (value > MAX_SAFE_INTEGER || value < MIN_SAFE_INTEGER) {`);
    lines.push(`                fail("integer parameter exceeds the safe integer range; pass an exact decimal string");`);
    lines.push(`            }`);
    lines.push(`            return value == 0 ? "0" : String(value);`);
    lines.push(`        }`);
    lines.push(`        text = String(value);`);
    lines.push(`        if (!/^-?(0|[1-9][0-9]*)$/.test(text)) {`);
    lines.push(`            fail("integer parameter must be a canonical decimal string");`);
    lines.push(`        }`);
    lines.push(`        if (text == "-0") {`);
    lines.push(`            text = "0";`);
    lines.push(`        }`);
    lines.push(`        if (!int64TextInRange(text)) {`);
    lines.push(`            fail("integer parameter is outside the signed 64-bit range");`);
    lines.push(`        }`);
    lines.push(`        return text;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function int64FromWire(text, exact) {`);
    lines.push(`        var negative;`);
    lines.push(`        var digits;`);
    lines.push(`        var safeLimit = "9007199254740991";`);
    lines.push(`        if (!/^(0|[1-9][0-9]*|-[1-9][0-9]*)$/.test(text) || !int64TextInRange(text)) {`);
    lines.push(`            fail("integer wire value is not a canonical signed 64-bit decimal");`);
    lines.push(`        }`);
    lines.push(`        if (exact) {`);
    lines.push(`            return text;`);
    lines.push(`        }`);
    lines.push(`        negative = text.charAt(0) == "-";`);
    lines.push(`        digits = negative ? text.substring(1) : text;`);
    lines.push(`        digits = digits.replace(/^0+/, "");`);
    lines.push(`        if (digits.length == 0) {`);
    lines.push(`            digits = "0";`);
    lines.push(`        }`);
    lines.push(`        if (digits.length > safeLimit.length || (digits.length == safeLimit.length && digits > safeLimit)) {`);
    lines.push(`            fail("integer value " + text + " exceeds the safe integer range; request exact mode for the decimal string");`);
    lines.push(`        }`);
    lines.push(`        return negative ? -Number(digits) : Number(digits);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function realToWire(value) {`);
    lines.push(`        if (typeof value != "number" || !isFinite(value)) {`);
    lines.push(`            fail("real parameter must be a finite number");`);
    lines.push(`        }`);
    lines.push(`        return String(value);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function realFromWire(text) {`);
    lines.push(`        var value;`);
    lines.push(`        if (!/^-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][+-]?[0-9]+)?$/.test(text)) {`);
    lines.push(`            fail("real wire value is not a canonical decimal token");`);
    lines.push(`        }`);
    lines.push(`        value = Number(text);`);
    lines.push(`        if (!isFinite(value)) {`);
    lines.push(`            fail("real wire value is not finite");`);
    lines.push(`        }`);
    lines.push(`        return value;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function splitTokens(text) {`);
    lines.push(`        return String(text).split("|");`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function parseUnsigned(text, label, maxText, requirePositive) {`);
    lines.push(`        var value;`);
    lines.push(`        if (!/^(0|[1-9][0-9]*)$/.test(text)) {`);
    lines.push(`            fail(label + " must be a canonical unsigned decimal integer");`);
    lines.push(`        }`);
    lines.push(`        if (requirePositive && text == "0") {`);
    lines.push(`            fail(label + " must be positive");`);
    lines.push(`        }`);
    lines.push(`        if (text.length > maxText.length || (text.length == maxText.length && text > maxText)) {`);
    lines.push(`            fail(label + " is out of range");`);
    lines.push(`        }`);
    lines.push(`        value = Number(text);`);
    lines.push(`        if (!isFinite(value) || Math.floor(value) != value) {`);
    lines.push(`            fail(label + " is not representable exactly");`);
    lines.push(`        }`);
    lines.push(`        return value;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function parseFields(rest) {`);
    lines.push(`        var bar = rest.indexOf("|");`);
    lines.push(`        var head = bar < 0 ? rest : rest.substring(0, bar);`);
    lines.push(`        var count;`);
    lines.push(`        var tokens;`);
    lines.push(`        var fields = [];`);
    lines.push(`        var i;`);
    lines.push(`        if (head.charAt(0) != ":") {`);
    lines.push(`            fail("malformed row wire");`);
    lines.push(`        }`);
    lines.push(`        count = parseUnsigned(head.substring(1), "row field count", "9007199254740991", false);`);
    lines.push(`        tokens = bar < 0 ? [] : splitTokens(rest.substring(bar + 1));`);
    lines.push(`        if (tokens.length != count * 2) {`);
    lines.push(`            fail("row wire field count mismatch");`);
    lines.push(`        }`);
    lines.push(`        for (i = 0; i < count; i += 1) {`);
    lines.push(`            fields[fields.length] = { tag: tokens[i * 2], value: tokens[i * 2 + 1] };`);
    lines.push(`        }`);
    lines.push(`        return fields;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function parseRows(rest) {`);
    lines.push(`        var bar = rest.indexOf("|");`);
    lines.push(`        var head = bar < 0 ? rest : rest.substring(0, bar);`);
    lines.push(`        var rowCount;`);
    lines.push(`        var tokens = bar < 0 ? [] : splitTokens(rest.substring(bar + 1));`);
    lines.push(`        var cursor = 0;`);
    lines.push(`        var rows = [];`);
    lines.push(`        var i;`);
    lines.push(`        var j;`);
    lines.push(`        var fieldCount;`);
    lines.push(`        var fields;`);
    lines.push(`        if (head.charAt(0) != ":") {`);
    lines.push(`            fail("malformed rows wire");`);
    lines.push(`        }`);
    lines.push(`        rowCount = parseUnsigned(head.substring(1), "row count", "9007199254740991", false);`);
    lines.push(`        for (i = 0; i < rowCount; i += 1) {`);
    lines.push(`            if (cursor >= tokens.length) {`);
    lines.push(`                fail("rows wire ended before row field count");`);
    lines.push(`            }`);
    lines.push(`            fieldCount = parseUnsigned(tokens[cursor], "row field count", "9007199254740991", false);`);
    lines.push(`            cursor += 1;`);
    lines.push(`            if (cursor + fieldCount * 2 > tokens.length) {`);
    lines.push(`                fail("rows wire ended before all row fields");`);
    lines.push(`            }`);
    lines.push(`            fields = [];`);
    lines.push(`            for (j = 0; j < fieldCount; j += 1) {`);
    lines.push(`                fields[fields.length] = { tag: tokens[cursor], value: tokens[cursor + 1] };`);
    lines.push(`                cursor += 2;`);
    lines.push(`            }`);
    lines.push(`            rows[rows.length] = fields;`);
    lines.push(`        }`);
    lines.push(`        if (cursor != tokens.length) {`);
    lines.push(`            fail("rows wire contains trailing data");`);
    lines.push(`        }`);
    lines.push(`        return rows;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function parseWire(text) {`);
    lines.push(`        var wire = String(text);`);
    lines.push(`        var body;`);
    lines.push(`        var kind;`);
    lines.push(`        var rest;`);
    lines.push(`        var colon;`);
    lines.push(`        var status;`);
    lines.push(`        if (wire.substring(0, 3) != WIRE_PREFIX) {`);
    lines.push(`            fail("invalid bridge wire version");`);
    lines.push(`        }`);
    lines.push(`        body = wire.substring(3);`);
    lines.push(`        kind = body.charAt(0);`);
    lines.push(`        rest = body.substring(1);`);
    lines.push(`        if (kind == "O") {`);
    lines.push(`            if (rest.length != 0) fail("ok wire contains trailing data");`);
    lines.push(`            return { kind: "ok" };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "N") {`);
    lines.push(`            if (rest.length != 0) fail("none wire contains trailing data");`);
    lines.push(`            return { kind: "none" };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "E") {`);
    lines.push(`            if (rest.charAt(0) != ":") fail("malformed error wire");`);
    lines.push(`            colon = rest.indexOf(":", 1);`);
    lines.push(`            if (colon < 0) {`);
    lines.push(`                fail("malformed error wire");`);
    lines.push(`            }`);
    lines.push(`            status = int64FromWire(rest.substring(1, colon), false);`);
    lines.push(`            if (status < -2147483648 || status > 2147483647) fail("error status is out of int32 range");`);
    lines.push(`            return {`);
    lines.push(`                kind: "error",`);
    lines.push(`                status: status,`);
    lines.push(`                message: hexToUtf8(rest.substring(colon + 1))`);
    lines.push(`            };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "H") {`);
    lines.push(`            if (rest.charAt(0) != ":") fail("malformed handle wire");`);
    lines.push(`            return { kind: "handle", handle: parseUnsigned(rest.substring(1), "handle", "2147483647", true) };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "C") {`);
    lines.push(`            if (rest.charAt(0) != ":") fail("malformed changes wire");`);
    lines.push(`            return { kind: "changes", changes: parseUnsigned(rest.substring(1), "changes", "2147483647", false) };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "R") {`);
    lines.push(`            return { kind: "row", fields: parseFields(rest) };`);
    lines.push(`        }`);
    lines.push(`        if (kind == "L") {`);
    lines.push(`            return { kind: "rows", rows: parseRows(rest) };`);
    lines.push(`        }`);
    lines.push(`        fail("unknown bridge wire kind: " + kind);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function decodeField(type, nullable, field, exact) {`);
    lines.push(`        if (field.tag == "n") {`);
    lines.push(`            if (!nullable) fail("bridge sent null for a non-nullable " + type + " column");`);
    lines.push(`            if (field.value.length != 0) fail("null field must have an empty payload");`);
    lines.push(`            return null;`);
    lines.push(`        }`);
    lines.push(`        if (field.tag == "i" || field.tag == "e") {`);
    lines.push(`            if (type != "integer") {`);
    lines.push(`                fail("bridge sent an integer field for a " + type + " column");`);
    lines.push(`            }`);
    lines.push(`            return int64FromWire(hexToUtf8(field.value), field.tag == "e" ? true : exact);`);
    lines.push(`        }`);
    lines.push(`        if (field.tag == "t") {`);
    lines.push(`            if (type != "text") fail("bridge sent a text field for a " + type + " column");`);
    lines.push(`            return hexToUtf8(field.value);`);
    lines.push(`        }`);
    lines.push(`        if (field.tag == "r") {`);
    lines.push(`            if (type != "real") fail("bridge sent a real field for a " + type + " column");`);
    lines.push(`            return realFromWire(hexToUtf8(field.value));`);
    lines.push(`        }`);
    lines.push(`        if (field.tag == "b") {`);
    lines.push(`            if (type != "blob") fail("bridge sent a blob field for a " + type + " column");`);
    lines.push(`            return normalizeHex(field.value);`);
    lines.push(`        }`);
    lines.push(`        fail("unknown field tag: " + field.tag);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function decodeRow(meta, fields, esdbOptions) {`);
    lines.push(`        var exact = esdbOptions && esdbOptions.exactIntegers === true;`);
    lines.push(`        var row = {};`);
    lines.push(`        var i;`);
    lines.push(`        if (fields.length != meta.columns.length) {`);
    lines.push(`            fail("row wire field count mismatch");`);
    lines.push(`        }`);
    lines.push(`        for (i = 0; i < meta.columns.length; i += 1) {`);
    lines.push(`            row[meta.columns[i]] = decodeField(meta.columnTypes[i], meta.columnNullable[i], fields[i], exact);`);
    lines.push(`        }`);
    lines.push(`        return row;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function encodeParam(queryName, index, value) {`);
    lines.push(`        var param = QUERIES[queryName].params[index];`);
    lines.push(`        if (value === null || value === void 0) {`);
    lines.push(`            if (!param.nullable) {`);
    lines.push(`                fail("parameter " + param.name + " may not be null");`);
    lines.push(`            }`);
    lines.push(`            return "n";`);
    lines.push(`        }`);
    lines.push(`        if (param.type == "integer") {`);
    lines.push(`            return "i:" + int64ToWire(value);`);
    lines.push(`        }`);
    lines.push(`        if (param.type == "text") {`);
    lines.push(`            return "t:" + utf8ToHex(value);`);
    lines.push(`        }`);
    lines.push(`        if (param.type == "real") {`);
    lines.push(`            return "r:" + realToWire(value);`);
    lines.push(`        }`);
    lines.push(`        if (param.type == "blob") {`);
    lines.push(`            return "b:" + normalizeHex(value);`);
    lines.push(`        }`);
    lines.push(`        fail("unknown parameter type: " + param.type);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function decodeReply(queryName, wire, esdbOptions) {`);
    lines.push(`        var meta = QUERIES[queryName];`);
    lines.push(`        var parsed = parseWire(wire);`);
    lines.push(`        var rows = [];`);
    lines.push(`        var i;`);
    lines.push(`        if (parsed.kind == "error") {`);
    lines.push(`            fail(queryName + ": " + parsed.message + " (status " + parsed.status + ")");`);
    lines.push(`        }`);
    lines.push(`        if (meta.cardinality == "one") {`);
    lines.push(`            if (parsed.kind == "none") {`);
    lines.push(`                return null;`);
    lines.push(`            }`);
    lines.push(`            if (parsed.kind != "row") {`);
    lines.push(`                fail(queryName + ": unexpected bridge reply");`);
    lines.push(`            }`);
    lines.push(`            return decodeRow(meta, parsed.fields, esdbOptions);`);
    lines.push(`        }`);
    lines.push(`        if (meta.cardinality == "many") {`);
    lines.push(`            if (parsed.kind != "rows") {`);
    lines.push(`                fail(queryName + ": unexpected bridge reply");`);
    lines.push(`            }`);
    lines.push(`            for (i = 0; i < parsed.rows.length; i += 1) {`);
    lines.push(`                rows[rows.length] = decodeRow(meta, parsed.rows[i], esdbOptions);`);
    lines.push(`            }`);
    lines.push(`            return rows;`);
    lines.push(`        }`);
    lines.push(`        if (parsed.kind != "changes") {`);
    lines.push(`            fail(queryName + ": unexpected bridge reply");`);
    lines.push(`        }`);
    lines.push(`        return parsed.changes;`);
    lines.push(`    }`);
    lines.push(``);
}

export function generateEs3(ir, ctx) {
    const schema = ir.schema.name;
    const global = es3GlobalName(schema);
    const plans = ir.queries.map((query) => {
        const table = tableByName(ir, query.table);
        if (table === null) {
            throw new Error(`query "${query.name}" targets unavailable table "${query.table}"`);
        }
        return planQuery(ir, schema, table, query);
    });
    const lines = [];

    lines.push(`/*`);
    lines.push(` * Generated by ${ctx.compilerName} ${ctx.compilerVersion}. DO NOT EDIT.`);
    lines.push(` * IR: ${ir.ir_version} sha256:${ctx.irHash}`);
    if (ctx.source) {
        lines.push(` * Source: ${ctx.source}`);
    }
    lines.push(` *`);
    lines.push(` * ES3-safe ExtendScript repository facade for schema "${schema}".`);
    lines.push(` *`);
    lines.push(` * This facade calls named generated bridge operations only. It never`);
    lines.push(` * builds, sends, or accepts SQL text. Wire contract and operation list:`);
    lines.push(` * bridge/${schema}_orm_bridge.h.`);
    lines.push(` */`);
    lines.push(`var ${global} = (function () {`);
    lines.push(`    var IR_HASH = ${JSON.stringify(ctx.irHash)};`);
    lines.push(`    var WIRE_PREFIX = "U1:";`);
    lines.push(`    var BRIDGE_LIBRARY = ${JSON.stringify(bridgeDefaultLibrary(schema))};`);
    lines.push(`    var MAX_SAFE_INTEGER = 9007199254740991;`);
    lines.push(`    var MIN_SAFE_INTEGER = -9007199254740991;`);
    lines.push(`    var COLUMNS = [`);

    const table = ir.tables[0];
    table.columns.forEach((column, index) => {
        const comma = index + 1 < table.columns.length ? "," : "";
        lines.push(`        ${JSON.stringify(column.name)}${comma}`);
    });
    lines.push(`    ];`);
    lines.push(`    var COLUMN_TYPES = [`);
    table.columns.forEach((column, index) => {
        const comma = index + 1 < table.columns.length ? "," : "";
        lines.push(`        ${JSON.stringify(column.type)}${comma}`);
    });
    lines.push(`    ];`);
    lines.push(`    var COLUMN_NULLABLE = [`);
    table.columns.forEach((column, index) => {
        const comma = index + 1 < table.columns.length ? "," : "";
        lines.push(`        ${column.nullable === true ? "true" : "false"}${comma}`);
    });
    lines.push(`    ];`);
    lines.push(``);
    lines.push(`    var QUERIES = {`);
    plans.forEach((plan, index) => {
        const comma = index + 1 < plans.length ? "," : "";
        lines.push(`        ${JSON.stringify(plan.method)}: {`);
        lines.push(`            bridge: ${JSON.stringify(plan.bridge)},`);
        lines.push(`            cardinality: ${JSON.stringify(plan.cardinality)},`);
        lines.push(`            columns: ${JSON.stringify(plan.columns)},`);
        lines.push(`            columnTypes: ${JSON.stringify(plan.columnTypes)},`);
        lines.push(`            columnNullable: ${JSON.stringify(plan.columnNullable)},`);
        lines.push(`            params: [`);
        plan.params.forEach((param, paramIndex) => {
            const paramComma = paramIndex + 1 < plan.params.length ? "," : "";
            lines.push(
                `                { name: ${JSON.stringify(param.name)}, type: ${JSON.stringify(param.type)}, nullable: ${
                    param.nullable ? "true" : "false"
                } }${paramComma}`
            );
        });
        lines.push(`            ]`);
        lines.push(`        }${comma}`);
    });
    lines.push(`    };`);
    lines.push(``);
    lines.push(`    var bridge = null;`);
    lines.push(`    var loadedSpec = null;`);
    lines.push(`    var openHandles = 0;`);
    lines.push(``);
    lines.push(`    function fail(message) {`);
    lines.push(`        throw new Error(${JSON.stringify(`${global}: `)} + message);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function ensureBridge() {`);
    lines.push(`        if (!bridge) {`);
    lines.push(`            load();`);
    lines.push(`        }`);
    lines.push(`        return bridge;`);
    lines.push(`    }`);
    lines.push(``);
    emitHelpers(global, lines);

    lines.push(`    function load(spec) {`);
    lines.push(`        var librarySpec;`);
    lines.push(`        var candidate = null;`);
    lines.push(`        var version = "";`);
    lines.push(`        var ping = 0;`);
    lines.push(`        if (bridge) {`);
    lines.push(`            return api;`);
    lines.push(`        }`);
    lines.push(`        if (typeof ExternalObject == "undefined") {`);
    lines.push(`            fail("ExternalObject is unavailable in this host");`);
    lines.push(`        }`);
    lines.push(`        librarySpec = spec ? String(spec) : BRIDGE_LIBRARY;`);
    lines.push(`        try {`);
    lines.push(`            candidate = new ExternalObject(librarySpec);`);
    lines.push(`            version = candidate ? String(candidate.ormVersion(0)) : "";`);
    lines.push(`            ping = candidate ? candidate.ormPing(0) : 0;`);
    lines.push(`        } catch (e) {`);
    lines.push(`            candidate = null;`);
    lines.push(`            version = "";`);
    lines.push(`        }`);
    lines.push(`        if (!candidate || version != IR_HASH || ping !== 42) {`);
    lines.push(`            if (candidate) {`);
    lines.push(`                try {`);
    lines.push(`                    candidate.unload();`);
    lines.push(`                } catch (ignore) {`);
    lines.push(`                }`);
    lines.push(`            }`);
    lines.push(`            bridge = null;`);
    lines.push(`            loadedSpec = null;`);
    lines.push(`            fail("bridge load failed or IR hash mismatch (expected " + IR_HASH + ", received " + version + ")");`);
    lines.push(`        }`);
    lines.push(`        bridge = candidate;`);
    lines.push(`        loadedSpec = librarySpec;`);
    lines.push(`        return api;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function unload() {`);
    lines.push(`        if (!bridge) {`);
    lines.push(`            return true;`);
    lines.push(`        }`);
    lines.push(`        if (openHandles != 0) {`);
    lines.push(`            fail("cannot unload while " + openHandles + " database handle(s) are open");`);
    lines.push(`        }`);
    lines.push(`        try {`);
    lines.push(`            bridge.unload();`);
    lines.push(`        } catch (e) {`);
    lines.push(`            fail("bridge unload failed: " + String(e));`);
    lines.push(`        }`);
    lines.push(`        bridge = null;`);
    lines.push(`        loadedSpec = null;`);
    lines.push(`        return true;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function open(pathValue) {`);
    lines.push(`        var xo = ensureBridge();`);
    lines.push(`        var pathText = pathValue && typeof pathValue.fsName == "string" ? pathValue.fsName : String(pathValue);`);
    lines.push(`        var parsed = parseWire(String(xo.ormOpen(0, utf8ToHex(pathText))));`);
    lines.push(`        if (parsed.kind == "error") {`);
    lines.push(`            fail("open: " + parsed.message + " (status " + parsed.status + ")");`);
    lines.push(`        }`);
    lines.push(`        if (parsed.kind != "handle") {`);
    lines.push(`            fail("open: unexpected bridge reply");`);
    lines.push(`        }`);
    lines.push(`        openHandles += 1;`);
    lines.push(`        return parsed.handle;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function close(handle) {`);
    lines.push(`        var xo = ensureBridge();`);
    lines.push(`        var parsed = parseWire(String(xo.ormClose(handle)));`);
    lines.push(`        if (parsed.kind == "error") {`);
    lines.push(`            fail("close: " + parsed.message + " (status " + parsed.status + ")");`);
    lines.push(`        }`);
    lines.push(`        if (openHandles > 0) {`);
    lines.push(`            openHandles -= 1;`);
    lines.push(`        }`);
    lines.push(`        return true;`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function lastError() {`);
    lines.push(`        var xo = ensureBridge();`);
    lines.push(`        var parsed = parseWire(String(xo.ormLastError(0)));`);
    lines.push(`        if (parsed.kind == "ok") {`);
    lines.push(`            return { ok: true, status: 0, message: "" };`);
    lines.push(`        }`);
    lines.push(`        if (parsed.kind == "error") {`);
    lines.push(`            return { ok: false, status: parsed.status, message: parsed.message };`);
    lines.push(`        }`);
    lines.push(`        fail("lastError: unexpected bridge reply");`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function invoke(handle, queryName, args, esdbOptions) {`);
    lines.push(`        var xo = ensureBridge();`);
    lines.push(`        var wire;`);
    lines.push(`        if (!QUERIES[queryName]) {`);
    lines.push(`            fail("unknown generated operation: " + queryName);`);
    lines.push(`        }`);
    plans.forEach((plan, index) => {
        const keyword = index === 0 ? "if" : "} else if";
        const encoded = plan.params
            .map((param, paramIndex) => `encodeParam(queryName, ${paramIndex}, args[${paramIndex}])`)
            .join(", ");
        lines.push(`        ${keyword} (queryName == ${JSON.stringify(plan.method)}) {`);
        lines.push(`            wire = xo.${plan.bridge}(handle${encoded.length > 0 ? `, ${encoded}` : ""});`);
    });
    if (plans.length > 0) {
        lines.push(`        } else {`);
        lines.push(`            fail("generated operation has no bridge call: " + queryName);`);
        lines.push(`        }`);
    } else {
        lines.push(`        fail("no generated operations are defined for this schema");`);
    }
    lines.push(`        return decodeReply(queryName, String(wire), esdbOptions);`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    function repository(handle) {`);
    lines.push(`        return {`);
    plans.forEach((plan, index) => {
        const comma = index + 1 < plans.length ? "," : "";
        const objectStyle = plan.kind === "insert" || plan.kind === "upsert";
        const args = objectStyle ? "values" : plan.params.map((param) => param.name).join(", ");
        const argsWithOptions = args.length > 0 ? `${args}, esdbOptions` : "esdbOptions";
        let valuesExpression;
        if (objectStyle) {
            valuesExpression = plan.params.map((param) => `values[${JSON.stringify(param.name)}]`).join(", ");
        } else {
            valuesExpression = plan.params.map((param) => param.name).join(", ");
        }
        lines.push(`            ${plan.method}: function (${argsWithOptions}) {`);
        lines.push(`                return invoke(handle, ${JSON.stringify(plan.method)}, [${valuesExpression}], esdbOptions);`);
        lines.push(`            }${comma}`);
    });
    lines.push(`        };`);
    lines.push(`    }`);
    lines.push(``);
    lines.push(`    var OPERATION_NAMES = [`);
    plans.forEach((plan, index) => {
        const comma = index + 1 < plans.length ? "," : "";
        lines.push(`        ${JSON.stringify(plan.method)}${comma}`);
    });
    lines.push(`    ];`);
    lines.push(``);
    lines.push(`    var api = {`);
    lines.push(`        load: load,`);
    lines.push(`        unload: unload,`);
    lines.push(`        open: open,`);
    lines.push(`        close: close,`);
    lines.push(`        repository: repository,`);
    lines.push(`        lastError: lastError,`);
    lines.push(`        irHash: IR_HASH,`);
    lines.push(`        columns: COLUMNS,`);
    lines.push(`        operations: OPERATION_NAMES`);
    lines.push(`    };`);
    lines.push(`    return api;`);
    lines.push(`}());`);
    lines.push(``);

    return [
        {
            relPath: `es3/${schema}_repository.jsx`,
            content: lines.join("\n")
        }
    ];
}
