/*
 * esdb-schema: TypeScript types, query metadata, and int64 boundary helpers.
 *
 * The TS artifact is a type/metadata surface only: it performs no I/O and
 * holds no connection state. Execution happens in the generated C++ and ES3
 * lanes. int64 helpers implement the IR v1 safe-integer policy.
 */

import { columnByName, deriveApiParams, deriveBindParams, tableByName } from "./ir.mjs";
import { emitQuerySql } from "./sql.mjs";
import { queryMethodName, toSnake, toUpperSnake } from "./naming.mjs";

function interfaceField(column, exact) {
    const name = column.name;
    if (column.nullable === true) {
        return `    ${name}: ${exact && column.type === "integer" ? "string" : tsType(column.type)} | null;`;
    }
    if (exact && column.type === "integer") {
        return `    ${name}: string;`;
    }
    return `    ${name}: ${tsType(column.type)};`;
}

function tsType(type) {
    switch (type) {
        case "integer":
        case "real":
            return "number";
        case "text":
        case "blob":
            return "string";
        default:
            throw new Error(`unsupported IR scalar type "${type}"`);
    }
}

export function generateTs(ir, ctx) {
    const schema = ir.schema.name;
    const upper = toUpperSnake(schema);
    const lines = [];

    lines.push(`// Generated by ${ctx.compilerName} ${ctx.compilerVersion}. DO NOT EDIT.`);
    lines.push(`// IR: ${ir.ir_version} sha256:${ctx.irHash}`);
    if (ctx.source) {
        lines.push(`// Source: ${ctx.source}`);
    }
    lines.push(`//`);
    lines.push(`// TypeScript types, query metadata, and int64 boundary helpers for schema "${schema}".`);
    lines.push(`// This module performs no I/O and holds no connection state; execution lives in`);
    lines.push(`// the generated C++ and ES3 lanes.`);
    lines.push(``);

    for (const table of ir.tables) {
        const pascal = table.name
            .split(/[^A-Za-z0-9]+/)
            .filter((part) => part.length > 0)
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
            .join("");
        lines.push(`export interface ${pascal}Row {`);
        for (const column of table.columns) {
            lines.push(interfaceField(column, false));
        }
        lines.push(`}`);
        lines.push(``);
        lines.push(`export interface ${pascal}RowExact {`);
        for (const column of table.columns) {
            lines.push(interfaceField(column, true));
        }
        lines.push(`}`);
        lines.push(``);
    }

    lines.push(`export interface QueryParamMeta {`);
    lines.push(`    name: string;`);
    lines.push(`    table: string | null;`);
    lines.push(`    column: string | null;`);
    lines.push(`    type: "integer" | "text" | "real" | "blob";`);
    lines.push(`    nullable: boolean;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export interface QueryMeta {`);
    lines.push(`    name: string;`);
    lines.push(`    kind: "select" | "insert" | "upsert" | "update" | "delete";`);
    lines.push(`    table: string;`);
    lines.push(`    cardinality: "one" | "many" | "changes";`);
    lines.push(`    params: QueryParamMeta[];`);
    lines.push(`    apiParams: QueryParamMeta[];`);
    lines.push(`    bindParams: QueryParamMeta[];`);
    lines.push(`    sql: string;`);
    lines.push(`}`);
    lines.push(``);

    for (const table of ir.tables) {
        const upperTable = toUpperSnake(table.name);
        lines.push(`export const ${upperTable}_COLUMNS: string[] = [`);
        table.columns.forEach((column, index) => {
            const comma = index + 1 < table.columns.length ? "," : "";
            lines.push(`    ${JSON.stringify(column.name)}${comma}`);
        });
        lines.push(`];`);
        lines.push(``);
    }

    lines.push(`export const ${upper}_SQL: { [query: string]: string } = {`);
    ir.queries.forEach((query, index) => {
        const table = ir.tables.find((candidate) => candidate.name === query.table);
        const { sql } = emitQuerySql(table, query, ir);
        const comma = index + 1 < ir.queries.length ? "," : "";
        lines.push(`    ${JSON.stringify(query.name)}: ${JSON.stringify(sql)}${comma}`);
    });
    lines.push(`};`);
    lines.push(``);

    lines.push(`export const ${upper}_QUERIES: QueryMeta[] = [`);
    ir.queries.forEach((query, queryIndex) => {
        const table = ir.tables.find((candidate) => candidate.name === query.table);
        const { sql } = emitQuerySql(table, query, ir);
        lines.push(`    {`);
        lines.push(`        name: ${JSON.stringify(query.name)},`);
        lines.push(`        kind: ${JSON.stringify(query.kind)},`);
        lines.push(`        table: ${JSON.stringify(query.table)},`);
        lines.push(`        cardinality: ${JSON.stringify(query.cardinality)},`);
        const emitParamArray = (property, queryParams) => {
            lines.push(`        ${property}: [`);
            queryParams.forEach((param, paramIndex) => {
                const owner = param.table === null || param.table === table.name ? table : tableByName(ir, param.table);
                const column = param.column === null || owner === null ? null : columnByName(owner, param.column);
                const paramComma = paramIndex + 1 < queryParams.length ? "," : "";
                lines.push(`            {`);
                lines.push(`                name: ${JSON.stringify(param.name)},`);
                lines.push(`                table: ${param.table === null ? "null" : JSON.stringify(param.table)},`);
                lines.push(`                column: ${param.column === null ? "null" : JSON.stringify(param.column)},`);
                lines.push(`                type: ${JSON.stringify(param.type)},`);
                lines.push(`                nullable: ${column !== null && column.nullable === true ? "true" : "false"}`);
                lines.push(`            }${paramComma}`);
            });
            lines.push(`        ],`);
        };
        const apiParams = deriveApiParams(table, query, ir);
        const bindParams = deriveBindParams(table, query, ir);
        emitParamArray("params", apiParams);
        emitParamArray("apiParams", apiParams);
        emitParamArray("bindParams", bindParams);
        lines.push(`        sql: ${JSON.stringify(sql)}`);
        lines.push(`    }${queryIndex + 1 < ir.queries.length ? "," : ""}`);
    });
    lines.push(`];`);
    lines.push(``);

    lines.push(`export const INT64_MIN_TEXT = "-9223372036854775808";`);
    lines.push(`export const INT64_MAX_TEXT = "9223372036854775807";`);
    lines.push(`export const INT64_SAFE_MIN = -9007199254740991;`);
    lines.push(`export const INT64_SAFE_MAX = 9007199254740991;`);
    lines.push(``);
    lines.push(`const INT64_TEXT_RE = /^-?(0|[1-9][0-9]*)$/;`);
    lines.push(``);
    lines.push(`export function canonicalInt64Text(value: string): string {`);
    lines.push(`    const text = String(value);`);
    lines.push(`    if (!INT64_TEXT_RE.test(text)) {`);
    lines.push(`        throw new RangeError(\`int64 value "\${text}" is not a canonical decimal integer\`);`);
    lines.push(`    }`);
    lines.push(`    const normalized = text === "-0" ? "0" : text;`);
    lines.push(`    const asBigInt = BigInt(normalized);`);
    lines.push(`    if (asBigInt < BigInt(INT64_MIN_TEXT) || asBigInt > BigInt(INT64_MAX_TEXT)) {`);
    lines.push(`        throw new RangeError(\`int64 value "\${text}" is outside the signed 64-bit range\`);`);
    lines.push(`    }`);
    lines.push(`    return normalized;`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function toInt64Param(value: number | string): string {`);
    lines.push(`    if (typeof value === "string") {`);
    lines.push(`        return canonicalInt64Text(value);`);
    lines.push(`    }`);
    lines.push(`    if (!Number.isInteger(value)) {`);
    lines.push(`        throw new RangeError(\`int64 parameter must be a whole number, received \${String(value)}\`);`);
    lines.push(`    }`);
    lines.push(`    if (!Number.isSafeInteger(value)) {`);
    lines.push(`        throw new RangeError("int64 parameter exceeds the safe integer range; pass an exact decimal string");`);
    lines.push(`    }`);
    lines.push(`    return String(value);`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function fromInt64Param(text: string, exact: boolean = false): number | string {`);
    lines.push(`    const normalized = canonicalInt64Text(text);`);
    lines.push(`    if (exact) {`);
    lines.push(`        return normalized;`);
    lines.push(`    }`);
    lines.push(`    const parsed = Number(normalized);`);
    lines.push(`    if (!Number.isSafeInteger(parsed)) {`);
    lines.push(`        throw new RangeError(`);
    lines.push(`            \`int64 value "\${normalized}" is outside the safe integer range; pass exact=true to receive a decimal string\``);
    lines.push(`        );`);
    lines.push(`    }`);
    lines.push(`    return parsed;`);
    lines.push(`}`);
    lines.push(``);

    return [
        {
            relPath: `ts/${toSnake(schema)}.ts`,
            content: lines.join("\n")
        }
    ];
}
